# apimodel = "accounts/fireworks/models/llama-v3p1-70b-instruct"
# URL = "https://api.fireworks.ai/inference"
apimodel = "meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo"
URL = "https://api.together.xyz"
# API_TOKEN = ""
API_TOKEN = ""
HF_TOKEN = ""